pipeline {
    agent {
        docker {
            image 'node:lts-slim' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build & Test') {
            steps {
                sh 'npm ci'
                sh 'npm run ci:jenkins-test'
            }
        }
    }
}
