pipeline {
    agent {
        docker {
            image 'node:lts-slim'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build & Test') {
            steps {
                sh 'apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb' // https://on.cypress.io/required-dependencies
                sh 'npm ci'
                sh 'npm run ci:jenkins-test'
            }
        }
    }
}
